### ISSUE TITLE
Help! I've gotten through all the way to step 9 and 10 but I can't access the feed

### ISSUE THREAD

**Issue by jperry1234** [guino/Merkury720#19]
I've been able to troubleshoot my way through the entire process with a Merkury Webcam and there is an existing patch. I can't seem to connect to my feed or change the address through the URLs provided in step 10. Thank you in advance for help!

**Comment by guino** [comment]
@jperry1234 a few questions:
-did you place the patched ppsapp in the root of the SD card ?
-are you able to telnet into the device ?
-did you check the size of your busybox file (1Mb+ when downloaded correctly)?
-does the device work normally with the tuya or manufacturer app ?

You can post a zip of your SD card contents (along with the firmware version) and I can take a look if you like, but chances are it is just one of the above items that needs to be fixed.

**Comment by jperry1234** [comment]
@guino Thanks for getting back fast, to answer you questions. Yes I placed the patch ppsapp in the root of the sd card, I haven't attempted to telnet into the device, I checked the sizes and they were different but I repeated the process and I still couldn't get the URLs in step 10 to work, and the device still works with the app.

**Comment by jperry1234** [comment]
Here is a link to the sd contents
https://www.dropbox.com/s/gu2c5eksoqou51x/github%20files.zip?dl=0

**Comment by jperry1234** [comment]
I prematurely closed the issue

**Comment by guino** [comment]
@jperry1234 I got your dropbox files, here's what I'm seeing:
1-There's no busybox in the root of the SD card (at least wasn't in the zip file), you need to download it from here: https://github.com/guino/Merkury720/blob/main/mmc/busybox?raw=true (should be about 1.1Mb in size)
2-I see ppsapp.omcsettings in the root of the SD card -- it appears to be patched properly comparing with the home/app/ppsapp file, but in order for it to work it needs to be named exactly `ppsapp`. I am not sure if you renamed it for testing or if that's the name you got when patching it, just letting you know it needs to be fixed before it will work.
3-there's no password hash set in the passwd file (required only if you want to use telnet)
4-your mjpeg.cgi and snap.cgi files don't seem to have the right address configured (required only if you want to use snap/mjpeg function) -- for your firmware I think the address should be 2c17b0
5-your play.cgi file doesn't have the right address configured (required only if you want to use play sound function) -- for your firmware I think the address should be 2c1fbc

If you take care of the above I expect it will work as expected -- you do need to boot with with the SD card inserted after the above is corrected, you should most likely hear 2 (two) startup sounds which indicates the patched ppsapp was loaded. Only after the 2nd startup sound is that you should try to use the RTSP function.
