### ISSUE TITLE
cannot open commandline?

### ISSUE THREAD

**Issue by sanscorp1** [guino/Merkury720#21]
Not an issue, but as a total noob I must be doing something wrong.

I want to use RTSP / Onvif but the web interface keeps asking me for a password when I'm trying to open the commandline. I copied the contents op MMC to the root of an SDHC card formatted as FAT32. 

admin:admin works for deviceinfo, but that's it.

{"devname":"Smart Home Camera","model":"Bullet 4S","serialno":"103020868","softwareversion":"4.0.7","hardwareversion":"B4S_V10_A2_2063","firmwareversion":"ppstrong-a3-tuya2_electro-4.0.7.20210624","identity":"M4G0039H5F01206552","authkey":"fJx5w7hCDpAWXJSL0FtNNQgvSr8X2N7z","deviceid":"pp01575076a614a24135","pid":"aaa","WiFi MAC":"84:7a:b6:03:d8:c1","ETH MAC":"84:7a:b6:03:d8:c1"}

I also find the information scattered, what do I need to do (step by step) to make this work?

Thanks!

**Comment by guino** [comment]
@sanscorp1 for that firmware you will follow the steps 1-2 listed [HERE](https://github.com/guino/Merkury720#rooting-and-customizng-the-device), then:

- Copy the 3 files posted [here](https://github.com/guino/Merkury1080P/tree/main/mmc) over of the mmc files on the SD card from the original instructions
- Create the ppsFactoryTool.txt file doing a RIGHT CLICK on this link: https://github.com/guino/Merkury720/raw/main/ppsFactoryTool.txt, then select "Save as.." and save this file to the root of the SD card. EDIT the file (do NOT create it new and do NOT copy/paste the contents of it) and **modify only** the ssid and password (The file requires specific format to work).
- Follow the steps 3-10 listed  [HERE](https://github.com/guino/Merkury720#rooting-and-customizng-the-device), but be sure to add :8090 to each URL in the steps after the IP (i.e. http://admin:056565099@IP:8090/proc/cmdline)

It has been pointed out that some of the URLs (i.e. /devices/deviceinfo) have user/password admin:admin like: http://admin:admin@ip:8090/devices/deviceinfo so if you can't get a URL to open with admin:056565099, try admin:admin as well (I don't have the device to know which URLs use which user/password combination). You should not need the /proc/cmdline to install the hack on your device (you don't need it for anything in the steps above).

**Comment by sanscorp1** [comment]
Thanks, I now got the files (hack, home etc.) on the SD card.
It was unclear to me that I needed all the files under the 720p repo and only had to overwrite the 3 files under 1080. I only looked at the 1080 files.

I put the correct (patched) ppsapp-onvif.ips on the root of the card and set a user and password in httpd.conf

with the URL admin:056565099 I got a login prompt, but when changed to admin:admin in the URL it works for device info but other pages are still "refused". I read this might occur in some cases.

What would be the RTSP URL for this version?

**Comment by guino** [comment]
@sanscorp1 you have to take one step at time here -- did you follow the steps I listed, if so: did it say 'done' on step 7? do you see the 'home/app/ppsapp' file in the SD card ?

**Comment by sanscorp1** [comment]
I get an error: "connection refused" so I never saw the step "done" and assumed it was correctly executed because the file "hack" is on the SD card.

I will start over tomorrow, downloading all the appropriate files, clean SD and reset the camera first.

Thank you for your very quick reply!
I'm sure it will work after a good night sleep.

**Comment by guino** [comment]
If you see the home/app/ppsapp in the SD car then it should have worked (even if you don't see 'done' in step 7) then it's just a matter of enabling RTSP either using telnet or with a patch.

**Comment by sanscorp1** [comment]
Does the name matter? Should I keep the format provided (i.e. ppsapp-onvif.ips) or should I rename it to just ppsapp like in the home/app folder?

By the way, even now when I started over, I cannot open any URL, it all results in "connection refused".
So I guess that is inherit for this model (Bullet 4S) under the brand LCS (sold by Action.nl).
I'lll wait 15 minutes before beginning step 8 to assure all files have been copied.


EDIT: I followed all instructions but now the camera is in a bootloop.
I can momentarily access it trough telnet before the next loop begins.
I did rename ppsapp-onvif.ips to ppsapp in the root of the SD.
The only thing I edited was passwd and cleanup.cgi where I changed the serial number.

I will next try this https://github.com/guino/Merkury1080P/issues/9#issuecomment-926414826 and delete the patched ppsapp from the SD root.

Edit2: I can cd into /home/cfg but there is no tuya_config.json.
Do I create the file myself or am I missing something here?

**Comment by guino** [comment]
@sanscorp1 did you get a home/app/ppsapp file **created automatically** during boot? 

I cannot say it enough: **DO NOT** run a ppsapp file in your device that was not already on your device (ie automatically copied to your sd card during boot) at the risk of bricking it.

The ips files are **patches** — there’s a whole set of steps (https://github.com/guino/ppsapp-rtsp/issues/1#issue-759079080) to use that ips patch file into modifying your original ppsapp before copying the modified ppsapp file into the root of the SD card. The steps are only useful if you got the original ppsapp created automatically in the SD card.

The /home/cfg/tuya_config.json file is only accessible using telnet as it is in the built-in firmware — it will **not** be in the SD card and if you’re using telnet and don’t see the file then you may not have enrolled the device using the phone app (which must be done).

Before proceeding I need to know:
1-did you get a home/app/ppsapp file automatically created in the SD card during boot of the device? You can delete the ‘home’ folder from the SD card and it should create it again during boot if the other files and hack was installed correctly (which sounds like it from your description)
3-is the device workings normally with the phone app?
2-are you able to telnet into the device? If so, you can execute this command: 
`cp /home/cfg/tuya_config.json /mnt/mmc01` to copy the json file to the SD card (if it exists).

**Comment by sanscorp1** [comment]
I thought the patched ppsapp in the repo was a complete pre-patched file and I only needed to follow the "how to patch" when the excisting patch would not be available.
I need to learn how to read better and take my time with these things.

After yesterday I performed a reset of the camera, so no it was not enrolled and I just did that again, tuya_config is now available trough telnet :)

I just patched my ppsapp, reading the how to page carefully.
The camera is still working on the phone and ovif device manager also show the livestream.

I thank you for your patience and assistance!
I hope my questions will be of help to future users.

**Comment by guino** [comment]
@sanscorp1 glad you got it working, thanks for letting us know.

We only have patch files available to download because we don’t want anyone bricking their devices by using the wrong file (plus there’s a legal aspect to avoid by doing that).
