### ISSUE TITLE
Hack Isn't applied

### ISSUE THREAD

**Issue by MsMaximeSeguin** [guino/Merkury720#22]
Hello,

I've got some issues applying the root hack to a Geeni 720p camera.

/home/ppsapp doesn't appear to be created when needed.

Here's the output of the various addresses : 

--------------------------------------------------
http://admin:056565099@192.168.17.115/proc/cmdline
-------------------------------------------------------------
mem=64M console=ttySAK0,115200n8 mtdparts=spi0.0:256k(bld)ro,64k(env)ro,64k(enc)ro,64k(sysflg)ro,2496k(sys),4608k(app),640k(cfg) ppsAppParts=5 ip=0 - ip=30;/mnt/mmc01/initrun.sh)&:::::;date>/tmp/hack;(sleep

--------------------------------------------------
http://admin:056565099@192.168.17.115/devices/deviceinfo
-------------------------------------------------------------
{"devname":"Smart Home Camera","model":"Mini 7C","serialno":"059104752","softwareversion":"2.7.6","hardwareversion":"M7C_AK_V10_1245","firmwareversion":"ppstrong-a2-tuya2_geeni-2.7.6.20210207","authkey":"CSA5ivaFswFiLAA8QA3ezAmB6rvtErR3","deviceid":"pp011e93f9b47ac32b86","identity":"MR1912030200903034","pid":"aaa","WiFi MAC":"7c:a7:b0:89:ef:b1"}

--------------------------------------------------
http://admin:056565099@192.168.17.115/proc/self/root/mnt/mmc01/hack
--------------------------------------------------
doesn't return anything (Error 500)

----------------------------------------------------------
SD CARD
----------------------------------------------------------
2022-04-27  06:04 PM    <DIR>          cgi-bin
2022-04-27  06:03 PM         1,109,128 busybox
2022-02-27  02:27 PM               636 custom.sh
2022-02-27  02:27 PM               131 env
2022-02-27  02:27 PM               285 hosts
2022-02-27  02:27 PM                16 httpd.conf
2022-02-27  02:27 PM             1,327 index.html
2022-02-27  02:27 PM               425 initrun.sh
2022-02-27  02:27 PM             7,956 jpeg-arm
2022-02-27  02:27 PM               131 mqtt_pub
2022-02-27  02:27 PM             1,064 offline.sh
2022-04-27  06:22 PM                40 passwd
2022-02-08  11:49 PM                54 ppsFactoryTool.txt
2022-02-27  02:27 PM               102 ppsMmcTool.txt
2022-02-27  02:27 PM               263 set
2022-02-27  02:27 PM               161 upload.html
2022-04-27  10:13 PM    <DIR>          SDT

Not sure what i'm doing wrong?

Thanks!

**Comment by guino** [comment]
@maxhunstar post a zip of your sd card files (without SDT folder) so I can review. The hack is installed so I just want to check you have the right initrun.sh and that it is not windows formatted or something.

please also post the response for:
http://admin:056565099@192.168.17.115/proc/self/root/tmp/hack

**Comment by MsMaximeSeguin** [comment]
Hi,

Thanks for the reply :-) Here's the zip and the response !


-----------------------------------------------------
http://admin:056565099@192.168.17.115/proc/self/root/tmp/hack
-----------------------------------------------------
Thu Jan  1 08:00:13 CST 1970

[sdr.zip](https://github.com/guino/Merkury720/files/8579062/sdr.zip)

**Comment by guino** [comment]
@maxhunstar your files seem fine and the response you provided indicates the hack is working -- the only question is why initrun.sh doesn't seem to be running -- from your listing it does appear to be in the ROOT of the SD card (not within any folders) -- can you just confirm it for me ? Also, can you confirm this is the same SD card used to install the hack (and you didn't re-format it after) ? Just trying to make sure the SD card is FAT32 formatted but it seems like it from the information you provided so far.

You can try to download/save this version of initrun.sh to the SD card just in case (right-click and select save as...) : https://github.com/guino/Merkury1080P/raw/main/mmc/initrun.sh it has a slightly different command more tolerant for a different file format they started using recently.

In all honestly if you just have the initrun.sh above in a FAT32 SD card during boot of the device you should be getting the home directory created -- so it may be worth trying a couple of SD cards if you have any available to see if it makes any difference.

**Comment by MsMaximeSeguin** [comment]
@guino As you mentioned both in the readme and in this issue, it was the SD card. Just went to the corner store and bought the smallest, shadiest SD and it worked! thanks for that hack and thanks for the help.

Prior to that I tried to format the 1st SD from another OS and that didn't work.

Quick question, once I patch the ppsapp, can I use the the patched file on another cam that came in the same package?

**Comment by guino** [comment]
@maxhunstar glad you got it working. If the devices have the same firmware version you should be able to use the same patched ppsapp , but you still have to install the hack and copy the other files for it to work.
