### ISSUE TITLE
Busybox version with more compiled features here!

### ISSUE THREAD

**Issue by russinnes** [guino/Merkury720#4]
Here is an (almost entirely complete) compiled busybox for the armv5 arch. This can be a drop in replacement (after renaming), or leave it as is and run it's commands from telnet/script/etc by calling the binary (/mnt/mmc01/busybox-merkury [options] as needed. Provides much more functionality if you want to hack more together! Examples include, routing, ftpd, etc. I use it for FTP to retrieve images for permanent storage. 
shell example: /mnt/mmc01/busybox-merkury tcpsvd -vE 0.0.0.0 21 /mnt/mmc01/busybox-merkury ftpd /mnt/mmc01
will serve /mnt/mmc01/ on all network interfaces

Attached;
[busybox-merkury.zip](https://github.com/guino/Merkury720/files/5882332/busybox-merkury.zip)

**Comment by guino** [comment]
@russinnes this seems to be exactly the same busybox as I posted in the repo (https://github.com/guino/Merkury720/blob/main/mmc/busybox?raw=true):

```
[wagner@xps13 Downloads]$ md5sum busybox-merkury
a64974c6ab29d50735cf9d027358ae3a  busybox-merkury
[wagner@xps13 Downloads]$ md5sum busybox
a64974c6ab29d50735cf9d027358ae3a  busybox
```

Maybe you were posted the wrong file ?

**Comment by russinnes** [comment]
Nope, although head scratching for the same md5. The applet functions are greatly expanded, load it up and have a look
 
Original:
        [, [[, arping, ash, awk, brctl, cat, chgrp, chmod, chown, chroot, cp,
        cut, date, df, dirname, dmesg, echo, env, expr, false, getty, grep,
        groups, halt, hostid, id, ifconfig, ifplugd, init, insmod, iostat,
        kill, linuxrc, ln, login, ls, lsmod, lsof, mdev, mkdir, mknod, modinfo,
        mount, mv, netstat, ping, ping6, poweroff, printenv, ps, pstree, pwd,
        reboot, rm, rmmod, route, sed, setconsole, setsid, sh, sleep, stat,
        tar, test, top, touch, udhcpc, udhcpc6, umount, vi, xargs

This one:
Currently defined functions:
        [, [[, acpid, add-shell, addgroup, adduser, adjtimex, arp, arping, ash, awk, base64, basename, beep, blkid, blockdev, bootchartd, brctl, bunzip2, bzcat, bzip2, cal,cat, catv, chat, chattr, chgrp, chmod, chown, chpasswd, chpst, chroot, chrt, chvt, cksum, clear, cmp, comm, conspy, cp, cpio, crond, crontab, cryptpw, cttyhack, cut,date, dc, dd, deallocvt, delgroup, deluser, depmod, devmem, df, dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, ed,egrep, eject, env, envdir, envuidgid, ether-wake, expand, expr, fakeidentd, false, fbset, fbsplash, fdflush, fdformat, fdisk, fgconsole, fgrep, find, findfs, flock,fold, free, freeramdisk, fsck, fsck.minix, fsync, ftpd, ftpget, ftpput, fuser, getopt, getty, grep, groups, gunzip, gzip, halt, hd, hdparm, head, hexdump, hostid, hostname, httpd, hush, hwclock, id, ifconfig, ifdown, ifenslave, ifplugd, ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc, ipcrm, ipcs, iplink,iproute, iprule, iptunnel, kbd_mode, kill, killall, killall5, klogd, last, less, linux32, linux64, linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread, losetup, lpd, lpq, lpr, ls, lsattr, lsmod, lsof, lspci, lsusb, lzcat, lzma, lzop, lzopcat, makedevs, makemime, man, md5sum, mdev, mesg, microcom, mkdir, mkdosfs,mke2fs, mkfifo, mkfs.ext2, mkfs.minix, mkfs.vfat, mknod, mkpasswd, mkswap, mktemp, modinfo, modprobe, more, mount, mountpoint, mpstat, mt, mv, nameif, nanddump,nandwrite, nbd-client, nc, netstat, nice, nmeter, nohup, nslookup, ntpd, od, openvt, passwd, patch, pgrep, pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap,popmaildir, poweroff, powertop, printenv, printf, ps, pscan, pstree, pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile, realpath, reboot,reformime, remove-shell, renice, reset, resize, rev, rm, rmdir, rmmod, route, rpm, rpm2cpio, rtcwake, run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay,sed, sendmail, seq, setarch, setconsole, setfont, setkeycodes, setlogcons, setserial, setsid, setuidgid, sh, sha1sum, sha256sum, sha3sum, sha512sum, showkey, slattach,sleep, smemcap, softlimit, sort, split, start-stop-daemon, stat, strings, stty, su, sulogin, sum, sv, svlogd, swapoff, swapon, switch_root, sync, sysctl, syslogd, tac,tail, tar, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time, timeout, top, touch, tr, traceroute, traceroute6, true, tty, ttysize, tunctl, udhcpc, udhcpd, udpsvd,umount, uname, unexpand, uniq, unix2dos, unlzma, unlzop, unxz, unzip, uptime, users, usleep, uudecode, uuencode, vconfig, vi, vlock, volname, wall, watch, watchdog,wc, wget, which, who, whoami, whois, xargs, xz, xzcat, yes, zcat, zcip

**Comment by bcmans** [comment]
telnet is there a how to that you have close by hand how to login to the camera?
thanks

**Comment by guino** [comment]
@russinnes The output you provided for the 1st busybox is the one in the **firmware** not the one I posted on the repo which is the same one you posted:

```
BusyBox v1.20.2 (2018-11-30 09:35:49 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

~ # busybox
BusyBox v1.20.2 (2018-11-30 09:35:49 CST) multi-call binary.
Copyright (C) 1998-2011 Erik Andersen, Rob Landley, Denys Vlasenko
and others. Licensed under GPLv2.
See source distribution for full notice.

Usage: busybox [function] [arguments]...
   or: busybox --list
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, arping, ash, awk, brctl, cat, chgrp, chmod, chown, chroot, cp,
        cut, date, df, dirname, dmesg, echo, env, expr, false, getty, grep,
        groups, halt, hostid, id, ifconfig, ifplugd, init, insmod, iostat,
        kill, linuxrc, ln, login, ls, lsmod, lsof, mdev, mkdir, mknod, modinfo,
        mount, mv, netstat, ping, ping6, poweroff, printenv, ps, pstree, pwd,
        reboot, rm, rmmod, route, sed, setconsole, setsid, sh, sleep, stat,
        tar, test, top, touch, udhcpc, udhcpc6, umount, vi, xargs

~ # /mnt/mmc01/busybox
BusyBox v1.21.1 (2013-07-08 10:13:48 CDT) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2012.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, acpid, add-shell, addgroup, adduser, adjtimex, arp, arping, ash, awk, base64, basename, beep,
        blkid, blockdev, bootchartd, brctl, bunzip2, bzcat, bzip2, cal, cat, catv, chat, chattr, chgrp,
        chmod, chown, chpasswd, chpst, chroot, chrt, chvt, cksum, clear, cmp, comm, conspy, cp, cpio, crond,
        crontab, cryptpw, cttyhack, cut, date, dc, dd, deallocvt, delgroup, deluser, depmod, devmem, df,
        dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, ed,
        egrep, eject, env, envdir, envuidgid, ether-wake, expand, expr, fakeidentd, false, fbset, fbsplash,
        fdflush, fdformat, fdisk, fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
        fsck.minix, fsync, ftpd, ftpget, ftpput, fuser, getopt, getty, grep, groups, gunzip, gzip, halt, hd,
        hdparm, head, hexdump, hostid, hostname, httpd, hush, hwclock, id, ifconfig, ifdown, ifenslave,
        ifplugd, ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc, ipcrm, ipcs, iplink,
        iproute, iprule, iptunnel, kbd_mode, kill, killall, killall5, klogd, last, less, linux32, linux64,
        linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread, losetup, lpd, lpq, lpr, ls, lsattr,
        lsmod, lsof, lspci, lsusb, lzcat, lzma, lzop, lzopcat, makedevs, makemime, man, md5sum, mdev, mesg,
        microcom, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix, mkfs.vfat, mknod, mkpasswd, mkswap,
        mktemp, modinfo, modprobe, more, mount, mountpoint, mpstat, mt, mv, nameif, nanddump, nandwrite,
        nbd-client, nc, netstat, nice, nmeter, nohup, nslookup, ntpd, od, openvt, passwd, patch, pgrep,
        pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap, popmaildir, poweroff, powertop, printenv,
        printf, ps, pscan, pstree, pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile,
        realpath, reboot, reformime, remove-shell, renice, reset, resize, rev, rm, rmdir, rmmod, route, rpm,
        rpm2cpio, rtcwake, run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed, sendmail,
        seq, setarch, setconsole, setfont, setkeycodes, setlogcons, setserial, setsid, setuidgid, sh,
        sha1sum, sha256sum, sha3sum, sha512sum, showkey, slattach, sleep, smemcap, softlimit, sort, split,
        start-stop-daemon, stat, strings, stty, su, sulogin, sum, sv, svlogd, swapoff, swapon, switch_root,
        sync, sysctl, syslogd, tac, tail, tar, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time,
        timeout, top, touch, tr, traceroute, traceroute6, true, tty, ttysize, tunctl, udhcpc, udhcpd, udpsvd,
        umount, uname, unexpand, uniq, unix2dos, unlzma, unlzop, unxz, unzip, uptime, users, usleep,
        uudecode, uuencode, vconfig, vi, vlock, volname, wall, watch, watchdog, wc, wget, which, who, whoami,
        whois, xargs, xz, xzcat, yes, zcat, zcip

~ # /mnt/mmc01/busybox-merkury 
BusyBox v1.21.1 (2013-07-08 10:13:48 CDT) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2012.
Licensed under GPLv2. See source distribution for detailed
copyright notices.

Usage: busybox [function [arguments]...]
   or: busybox --list[-full]
   or: busybox --install [-s] [DIR]
   or: function [arguments]...

        BusyBox is a multi-call binary that combines many common Unix
        utilities into a single executable.  Most people will create a
        link to busybox for each function they wish to use and BusyBox
        will act like whatever it was invoked as.

Currently defined functions:
        [, [[, acpid, add-shell, addgroup, adduser, adjtimex, arp, arping, ash, awk, base64, basename, beep,
        blkid, blockdev, bootchartd, brctl, bunzip2, bzcat, bzip2, cal, cat, catv, chat, chattr, chgrp,
        chmod, chown, chpasswd, chpst, chroot, chrt, chvt, cksum, clear, cmp, comm, conspy, cp, cpio, crond,
        crontab, cryptpw, cttyhack, cut, date, dc, dd, deallocvt, delgroup, deluser, depmod, devmem, df,
        dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, ed,
        egrep, eject, env, envdir, envuidgid, ether-wake, expand, expr, fakeidentd, false, fbset, fbsplash,
        fdflush, fdformat, fdisk, fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
        fsck.minix, fsync, ftpd, ftpget, ftpput, fuser, getopt, getty, grep, groups, gunzip, gzip, halt, hd,
        hdparm, head, hexdump, hostid, hostname, httpd, hush, hwclock, id, ifconfig, ifdown, ifenslave,
        ifplugd, ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc, ipcrm, ipcs, iplink,
        iproute, iprule, iptunnel, kbd_mode, kill, killall, killall5, klogd, last, less, linux32, linux64,
        linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread, losetup, lpd, lpq, lpr, ls, lsattr,
        lsmod, lsof, lspci, lsusb, lzcat, lzma, lzop, lzopcat, makedevs, makemime, man, md5sum, mdev, mesg,
        microcom, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix, mkfs.vfat, mknod, mkpasswd, mkswap,
        mktemp, modinfo, modprobe, more, mount, mountpoint, mpstat, mt, mv, nameif, nanddump, nandwrite,
        nbd-client, nc, netstat, nice, nmeter, nohup, nslookup, ntpd, od, openvt, passwd, patch, pgrep,
        pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap, popmaildir, poweroff, powertop, printenv,
        printf, ps, pscan, pstree, pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile,
        realpath, reboot, reformime, remove-shell, renice, reset, resize, rev, rm, rmdir, rmmod, route, rpm,
        rpm2cpio, rtcwake, run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed, sendmail,
        seq, setarch, setconsole, setfont, setkeycodes, setlogcons, setserial, setsid, setuidgid, sh,
        sha1sum, sha256sum, sha3sum, sha512sum, showkey, slattach, sleep, smemcap, softlimit, sort, split,
        start-stop-daemon, stat, strings, stty, su, sulogin, sum, sv, svlogd, swapoff, swapon, switch_root,
        sync, sysctl, syslogd, tac, tail, tar, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time,
        timeout, top, touch, tr, traceroute, traceroute6, true, tty, ttysize, tunctl, udhcpc, udhcpd, udpsvd,
        umount, uname, unexpand, uniq, unix2dos, unlzma, unlzop, unxz, unzip, uptime, users, usleep,
        uudecode, uuencode, vconfig, vi, vlock, volname, wall, watch, watchdog, wc, wget, which, who, whoami,
        whois, xargs, xz, xzcat, yes, zcat, zcip

```

**Comment by guino** [comment]
@bcmans if you applied the hack correctly you can login to the camera with `telnet 192.168.x.x` using the IP of the camera, the user and password will be whatever you defined in the passwd file which should have been done in step 9 of https://github.com/guino/Merkury720

**Comment by bcmans** [comment]
thanks I should have changed my question in how/what can i do with it. Will do a google about bussybox

**Comment by guino** [comment]
@bcmans you don't have to learn about busybox for anything. The purpose of telnet is to login to the camera and have full access to do whatever you need which in our case was more for editing the tuya_config.json file but I have made that unnecessary with the 'set' file and the latest custom.sh file I posted here: https://github.com/guino/Merkury720/tree/main/mmc -- the latest custom.sh also calls cleanup.cgi daily which I know is something you wanted.

**Comment by russinnes** [comment]
> @russinnes The output you provided for the 1st busybox is the one in the **firmware** not the one I posted on the repo which is the same one you posted:
> 
> ```
> BusyBox v1.20.2 (2018-11-30 09:35:49 CST) built-in shell (ash)
> Enter 'help' for a list of built-in commands.
> 
> ~ # busybox
> BusyBox v1.20.2 (2018-11-30 09:35:49 CST) multi-call binary.
> Copyright (C) 1998-2011 Erik Andersen, Rob Landley, Denys Vlasenko
> and others. Licensed under GPLv2.
> See source distribution for full notice.
> 
> Usage: busybox [function] [arguments]...
>    or: busybox --list
>    or: function [arguments]...
> 
>         BusyBox is a multi-call binary that combines many common Unix
>         utilities into a single executable.  Most people will create a
>         link to busybox for each function they wish to use and BusyBox
>         will act like whatever it was invoked as.
> 
> Currently defined functions:
>         [, [[, arping, ash, awk, brctl, cat, chgrp, chmod, chown, chroot, cp,
>         cut, date, df, dirname, dmesg, echo, env, expr, false, getty, grep,
>         groups, halt, hostid, id, ifconfig, ifplugd, init, insmod, iostat,
>         kill, linuxrc, ln, login, ls, lsmod, lsof, mdev, mkdir, mknod, modinfo,
>         mount, mv, netstat, ping, ping6, poweroff, printenv, ps, pstree, pwd,
>         reboot, rm, rmmod, route, sed, setconsole, setsid, sh, sleep, stat,
>         tar, test, top, touch, udhcpc, udhcpc6, umount, vi, xargs
> 
> ~ # /mnt/mmc01/busybox
> BusyBox v1.21.1 (2013-07-08 10:13:48 CDT) multi-call binary.
> BusyBox is copyrighted by many authors between 1998-2012.
> Licensed under GPLv2. See source distribution for detailed
> copyright notices.
> 
> Usage: busybox [function [arguments]...]
>    or: busybox --list[-full]
>    or: busybox --install [-s] [DIR]
>    or: function [arguments]...
> 
>         BusyBox is a multi-call binary that combines many common Unix
>         utilities into a single executable.  Most people will create a
>         link to busybox for each function they wish to use and BusyBox
>         will act like whatever it was invoked as.
> 
> Currently defined functions:
>         [, [[, acpid, add-shell, addgroup, adduser, adjtimex, arp, arping, ash, awk, base64, basename, beep,
>         blkid, blockdev, bootchartd, brctl, bunzip2, bzcat, bzip2, cal, cat, catv, chat, chattr, chgrp,
>         chmod, chown, chpasswd, chpst, chroot, chrt, chvt, cksum, clear, cmp, comm, conspy, cp, cpio, crond,
>         crontab, cryptpw, cttyhack, cut, date, dc, dd, deallocvt, delgroup, deluser, depmod, devmem, df,
>         dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, ed,
>         egrep, eject, env, envdir, envuidgid, ether-wake, expand, expr, fakeidentd, false, fbset, fbsplash,
>         fdflush, fdformat, fdisk, fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
>         fsck.minix, fsync, ftpd, ftpget, ftpput, fuser, getopt, getty, grep, groups, gunzip, gzip, halt, hd,
>         hdparm, head, hexdump, hostid, hostname, httpd, hush, hwclock, id, ifconfig, ifdown, ifenslave,
>         ifplugd, ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc, ipcrm, ipcs, iplink,
>         iproute, iprule, iptunnel, kbd_mode, kill, killall, killall5, klogd, last, less, linux32, linux64,
>         linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread, losetup, lpd, lpq, lpr, ls, lsattr,
>         lsmod, lsof, lspci, lsusb, lzcat, lzma, lzop, lzopcat, makedevs, makemime, man, md5sum, mdev, mesg,
>         microcom, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix, mkfs.vfat, mknod, mkpasswd, mkswap,
>         mktemp, modinfo, modprobe, more, mount, mountpoint, mpstat, mt, mv, nameif, nanddump, nandwrite,
>         nbd-client, nc, netstat, nice, nmeter, nohup, nslookup, ntpd, od, openvt, passwd, patch, pgrep,
>         pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap, popmaildir, poweroff, powertop, printenv,
>         printf, ps, pscan, pstree, pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile,
>         realpath, reboot, reformime, remove-shell, renice, reset, resize, rev, rm, rmdir, rmmod, route, rpm,
>         rpm2cpio, rtcwake, run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed, sendmail,
>         seq, setarch, setconsole, setfont, setkeycodes, setlogcons, setserial, setsid, setuidgid, sh,
>         sha1sum, sha256sum, sha3sum, sha512sum, showkey, slattach, sleep, smemcap, softlimit, sort, split,
>         start-stop-daemon, stat, strings, stty, su, sulogin, sum, sv, svlogd, swapoff, swapon, switch_root,
>         sync, sysctl, syslogd, tac, tail, tar, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time,
>         timeout, top, touch, tr, traceroute, traceroute6, true, tty, ttysize, tunctl, udhcpc, udhcpd, udpsvd,
>         umount, uname, unexpand, uniq, unix2dos, unlzma, unlzop, unxz, unzip, uptime, users, usleep,
>         uudecode, uuencode, vconfig, vi, vlock, volname, wall, watch, watchdog, wc, wget, which, who, whoami,
>         whois, xargs, xz, xzcat, yes, zcat, zcip
> 
> ~ # /mnt/mmc01/busybox-merkury 
> BusyBox v1.21.1 (2013-07-08 10:13:48 CDT) multi-call binary.
> BusyBox is copyrighted by many authors between 1998-2012.
> Licensed under GPLv2. See source distribution for detailed
> copyright notices.
> 
> Usage: busybox [function [arguments]...]
>    or: busybox --list[-full]
>    or: busybox --install [-s] [DIR]
>    or: function [arguments]...
> 
>         BusyBox is a multi-call binary that combines many common Unix
>         utilities into a single executable.  Most people will create a
>         link to busybox for each function they wish to use and BusyBox
>         will act like whatever it was invoked as.
> 
> Currently defined functions:
>         [, [[, acpid, add-shell, addgroup, adduser, adjtimex, arp, arping, ash, awk, base64, basename, beep,
>         blkid, blockdev, bootchartd, brctl, bunzip2, bzcat, bzip2, cal, cat, catv, chat, chattr, chgrp,
>         chmod, chown, chpasswd, chpst, chroot, chrt, chvt, cksum, clear, cmp, comm, conspy, cp, cpio, crond,
>         crontab, cryptpw, cttyhack, cut, date, dc, dd, deallocvt, delgroup, deluser, depmod, devmem, df,
>         dhcprelay, diff, dirname, dmesg, dnsd, dnsdomainname, dos2unix, du, dumpkmap, dumpleases, echo, ed,
>         egrep, eject, env, envdir, envuidgid, ether-wake, expand, expr, fakeidentd, false, fbset, fbsplash,
>         fdflush, fdformat, fdisk, fgconsole, fgrep, find, findfs, flock, fold, free, freeramdisk, fsck,
>         fsck.minix, fsync, ftpd, ftpget, ftpput, fuser, getopt, getty, grep, groups, gunzip, gzip, halt, hd,
>         hdparm, head, hexdump, hostid, hostname, httpd, hush, hwclock, id, ifconfig, ifdown, ifenslave,
>         ifplugd, ifup, inetd, init, insmod, install, ionice, iostat, ip, ipaddr, ipcalc, ipcrm, ipcs, iplink,
>         iproute, iprule, iptunnel, kbd_mode, kill, killall, killall5, klogd, last, less, linux32, linux64,
>         linuxrc, ln, loadfont, loadkmap, logger, login, logname, logread, losetup, lpd, lpq, lpr, ls, lsattr,
>         lsmod, lsof, lspci, lsusb, lzcat, lzma, lzop, lzopcat, makedevs, makemime, man, md5sum, mdev, mesg,
>         microcom, mkdir, mkdosfs, mke2fs, mkfifo, mkfs.ext2, mkfs.minix, mkfs.vfat, mknod, mkpasswd, mkswap,
>         mktemp, modinfo, modprobe, more, mount, mountpoint, mpstat, mt, mv, nameif, nanddump, nandwrite,
>         nbd-client, nc, netstat, nice, nmeter, nohup, nslookup, ntpd, od, openvt, passwd, patch, pgrep,
>         pidof, ping, ping6, pipe_progress, pivot_root, pkill, pmap, popmaildir, poweroff, powertop, printenv,
>         printf, ps, pscan, pstree, pwd, pwdx, raidautorun, rdate, rdev, readahead, readlink, readprofile,
>         realpath, reboot, reformime, remove-shell, renice, reset, resize, rev, rm, rmdir, rmmod, route, rpm,
>         rpm2cpio, rtcwake, run-parts, runlevel, runsv, runsvdir, rx, script, scriptreplay, sed, sendmail,
>         seq, setarch, setconsole, setfont, setkeycodes, setlogcons, setserial, setsid, setuidgid, sh,
>         sha1sum, sha256sum, sha3sum, sha512sum, showkey, slattach, sleep, smemcap, softlimit, sort, split,
>         start-stop-daemon, stat, strings, stty, su, sulogin, sum, sv, svlogd, swapoff, swapon, switch_root,
>         sync, sysctl, syslogd, tac, tail, tar, tcpsvd, tee, telnet, telnetd, test, tftp, tftpd, time,
>         timeout, top, touch, tr, traceroute, traceroute6, true, tty, ttysize, tunctl, udhcpc, udhcpd, udpsvd,
>         umount, uname, unexpand, uniq, unix2dos, unlzma, unlzop, unxz, unzip, uptime, users, usleep,
>         uudecode, uuencode, vconfig, vi, vlock, volname, wall, watch, watchdog, wc, wget, which, who, whoami,
>         whois, xargs, xz, xzcat, yes, zcat, zcip
> ```

<using telnet>
<want ftp>
<list busybox functions>
<no ftp>
<also no telnet>
<still using telnet>
<thinking too quickly>
<hey, lets share a busybox build with ftp and telnet>
<still using telnet>
<facepalm.jpg>
</thread>

**Comment by russinnes** [comment]
``

**Comment by russinnes** [comment]
{using telnet}
{hey, need some ftp}
{busybox doesnt contain ftp}
{busybox also doesnt contain telnet}
{share busybox build with ftp (and telnet)}
{still using telnet}
{acting faster than brain}
{facepalm.jpg}
{/thread>
