### ISSUE TITLE
Geeni Varian, cant get the hack to run. Tried alt boot location

### ISSUE THREAD

**Issue by GhostlyCrowd** [guino/Merkury720#8]
"devname":"Smart Home Camera","model":"Mini 7C","serialno":"XXXXXXXX","softwareversion":"2.7.7","hardwareversion":"MINI5C_V20B_H62","firmwareversion":"ppstrong-c4-tuya2_geeni-2.7.7.20210207"

2.7.7 closed port 80 but your work around to reopen it worked, i just cant get hacks installed.

Any ideas?

**Comment by guino** [comment]
@GhostlyCrowd 
From the information it shows mini 5c on the hardware section so I expect it to be like this:
https://github.com/guino/Merkury720/issues/7

And there’s no hack available, only known way is with a programmer: https://github.com/guino/Geeni720P

If you want to open the device, connect UART and/or programmer to try stuff we can, but otherwise not much we can do.

**Comment by GhostlyCrowd** [comment]
> @GhostlyCrowd
> From the information it shows mini 5c on the hardware section so I expect it to be like this:
> #7
> 
> And there’s no hack available, only known way is with a programmer: https://github.com/guino/Geeni720P
> 
> If you want to open the device, connect UART and/or programmer to try stuff we can, but otherwise not much we can do.

I am willing to open the device, but thats for another night im sick of looking at this cheap camera for the night lol I will post back when im ready.  In the mean time i will review #7 further although my camera appears to be newer then that (reset button is at the side not middle back)

Whats easier for you uart or should i just dump the eeprom? (both i can do easily) 

Just for reference this did not work either https://github.com/guino/BazzDoorbell/issues/11

**Comment by GhostlyCrowd** [comment]
Alright I've pulled the eeprom chip out, but im having an issue getting asprogrammer to indent it properly. 

What utility did you use to dump the chip?

**Comment by GhostlyCrowd** [comment]
Attached is the binwalk output Might be useful for #7 as well?
[output.txt](https://github.com/guino/Merkury720/files/6135045/output.txt)

**Comment by GhostlyCrowd** [comment]
UART Output

```
buffer = SPI Nor(cs 0) ID: 0x20 0x70 0x17
SPI Nor total size: 8MB
PPS:Nov 19 2018 10:45:15   meari_c4:  0
button
cmd:fatload mmc 0 0x81000000 ppsMmcTool.txt 1020
cmdBuf:fatload mmc 0 0x81000000 env;env import 81808000;run fcmd
envreset - reset env para

Unknown command 'run' - try 'help'
size:90
error: Pack header size error!
error: upgrade.bin unpack error!
envreset - reset env para

Unknown command 'run' - try 'help'
readLen:90
read err
magic err
ARM Linux Kernel Image (uncompressed)
2054864 Bytes = 2 MiB
   Loading Kernel Image ... magic err
___mem=23M ethphy=3#3  console=ttyAMA0,115200 loglevel=0 ppsdebug=off mtdparts=hi_sfc:192k(bld)ro,64k(env)ro,64k(enc)ro,64k(sysflg),2240k(sys),5m(app),448k(cfg) ppsAppParts=5 ip=192.168.1.10:::255.255.255.0 eth=08:88:12:41:37:60
Uncompressing Linux... done, booting the kernel.
```

**Comment by guino** [comment]
@GhostlyCrowd this looks exactly like the one I saw at https://github.com/guino/Geeni720P so the same steps described in the link should work - if you like feel free to email me a zip of your flash and I can modify it for you. (Sorry for the late answer - just got up, the flash dump tool I used is flashrom from linux).

**Comment by GhostlyCrowd** [comment]
> @GhostlyCrowd this looks exactly like the one I saw at https://github.com/guino/Geeni720P so the same steps described in the link should work - if you like feel free to email me a zip of your flash and I can modify it for you. (Sorry for the late answer - just got up, the flash dump tool I used is flashrom from linux).

That would be excellent im struggling with this Windows WSL linux   

I am emailing you right now to your email on your git profile.  Thanks fellow Canuck, were actually not far off im in London.

**Comment by guino** [comment]
@GhostlyCrowd That works. I don’t go to London often but it is cool to work with someone close by.

**Comment by GhostlyCrowd** [comment]
Too bad we couldn't just patch in a Uboot that supports the run commands you need.

I really appreciate the help, Ive got the thing on my desk all apart lol

**Comment by guino** [comment]
For anyone reading this issue, the solution here was the same as https://github.com/guino/Geeni720P where the flash chip was removed, a programmer was used to read/write it back with an extra boot script and the chip was soldered back.
