### ISSUE TITLE
[Feature Request] Maker snap and mjpeg resolution configurable

### ISSUE THREAD

**Issue by GhostlyCrowd** [guino/Merkury720#9]
Right now it appears snap and mjpeg are at the lowest supported 16:9 resolution of 640x360 Is it possible to bump it up to something hd, 1280x720 and 1920x1080 for example if wanted?  

Being able to repurpose these camera for mjpeg streaming for Octoprint is fantastic, so thanks for all theh ard work!

**Comment by guino** [comment]
@GhostlyCrowd sorry but I have tried to mess with it before, even located the parameter that defines which channel to use for jpeg and when I changed it the jpeg is just no longer generated. I am also concerned the internal buffers and free memory on the device would not be enough/available to handle the higher resolution + there are possible CPU concerns with using the high resolution.

What you can do is something like this on another machine to prepare a full-hd JPEG image:
ffmpeg -rtsp_transport tcp -i rtsp://IP_ADDRESS:8554 -f image2 -updatef 1 /tmp/img.jpg -y

Then the "/tmp/img.jpg" should have jpg file with the RTSP resolution -- the above constantly updates the image so it is up-to-date with the latest from the RTSP feed so you can basically just copy/serve/use the file as the high resolution snapshot.

There are different ways/options to do this with ffmpeg and other tools, but there's no easy way to run ffmpeg on the device itself either.

**Comment by guino** [comment]
If you don't want to constantly use the RTSP stream and write the file you can use something like this (on a schedlued/cron job etc) to write the image file every few seconds/minutes:

ffmpeg -i rtsp://10.10.10.7:8554 -vframes 1 -q:v 2 /tmp/img.jpg -y

That way you only run the tool to grab one frame, exit and then just run it again after so many seconds/minutes to make a new image.

**Comment by GhostlyCrowd** [comment]
Thanks for the reply, I will look into the work around, its not the end of the world the mjpeg quality is still reasonable enough to monitor a printer remotely.
